# Created with tools/winget_manifest.py in the Pawmodoro repo
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: beeftcg.Pawmodoro
PackageVersion: 2.17.0
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Python.Python.3.12
ReleaseDate: 2026-10-01
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/beeftcg-eng/pawmodoro/releases/download/v2.17.0/Pawmodoro-Setup.exe
    InstallerSha256: 9CFC49B95B4DA7F6883A6E67BE4D0E2F025B63985F4046194454A5E6A74AA2FC
ManifestType: installer
ManifestVersion: 1.12.0
