# Created with tools/winget_manifest.py in the Pawmodoro repo
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json
PackageIdentifier: beeftcg.Pawmodoro
PackageVersion: 2.17.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
